 <!--
    Nom : Keven Imbeault
    Date : 28 Janvier 2021
    But : Créer un fichier contenant seulement le pied de page d'un site afin de rendre la création de pages plus simple
-->

    <!-- Fichiers JS pour Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>

</html>